# Site settings
title: Technology Micro-Guides for Educators
email: skywriter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://teacher-guides.github.io" # the base hostname & protocol for your site
twitter_username: TomDSweeney
github_username:  skywriter2000

# Build settings
markdown: kramdown

# output settings
permalink: none # we won't be using dates in paths here.
